### ISSUE TITLE
Do not update event list selection and graph selection

### ISSUE THREAD

**Issue by tscode** [tscode/jtab#1]
If events arrive quickly, it is not a great experience to browse the history or check a section of the progress graphs, as they reset frequently.
For the history, we should probably offer a `track` button that gets disabled as soon as a user picks an event. For the graphs,
we have to look if `uplot` offers the ability to upgrade the plot data only, without changing the view. If this is not so, we have to hope that we can hook into the zooming functionality of `uplot`.

**Comment by leeoniya** [comment]
> For the graphs, we have to look if uplot offers the ability to upgrade the plot data only, without changing the view.

it does ;) `u.setData(newData, false)`: https://github.com/leeoniya/uPlot/blob/952d174558bacc217393bfd49abd401c247f3993/dist/uPlot.d.ts#L63-L64

**Comment by tscode** [comment]
Thanks alot, @leeoniya! This kind of service is extremely convenient ;) Among the (lean) js plotting libraries I looked at / tested, yours was my favorite one by far. So keep up the great work!

**Comment by leeoniya** [comment]
thanks!

btw, if you found any other libs i missed that would be interesting to add to the uPlot bench, let me know.

**Comment by tscode** [comment]
The user can now control if the event list selection / the graph view is updated or not by a `track` button (via d26b9a656413d4cdb7d2cfb29884516c9e011ff6)
